"""Added new models

Revision ID: 24fa71464260
Revises: c704da00c07c
Create Date: 2026-04-25 12:12:50.294374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24fa71464260'
down_revision: Union[str, Sequence[str], None] = 'c704da00c07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_participation_marks_week_number'), 'participation_marks', ['week_number'], unique=False)
    op.alter_column('users', 'preferred_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('UC', 'TUTOR', 'ADMIN', name='user_role'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('UC', 'TUTOR','ADMIN', name='user_role'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'preferred_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_participation_marks_week_number'), table_name='participation_marks')
    # ### end Alembic commands ###
