"""Make user profile fields compulsory

Revision ID: 32f309647d67
Revises: 65b1e8745f5c
Create Date: 2026-04-08 23:05:58.371711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32f309647d67'
down_revision: Union[str, Sequence[str], None] = '65b1e8745f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'preferred_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'UC', 'FACILITATOR'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'UC', 'FACILITATOR'),
               nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'preferred_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
