"""refactor_add_password_reset_token_to_users

Revision ID: 7008c81c5412
Revises: 24fa71464260
Create Date: 2026-05-16 12:15:12.608918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7008c81c5412'
down_revision: Union[str, Sequence[str], None] = '24fa71464260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_participation_marks_week_number_enabled_weeks'), 'participation_marks', type_='foreignkey')
    op.create_foreign_key(None, 'participation_marks', 'enabled_weeks', ['week_number'], ['week_number'], ondelete='CASCADE')
    op.alter_column('system_config', 'total_participation_points',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.add_column('users', sa.Column('password_reset_token_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_password_reset_token_hash'), 'users', ['password_reset_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_token_hash'), table_name='users')
    op.drop_column('users', 'password_reset_token_expires_at')
    op.drop_column('users', 'password_reset_token_hash')
    op.alter_column('system_config', 'total_participation_points',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'participation_marks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_participation_marks_week_number_enabled_weeks'), 'participation_marks', 'enabled_weeks', ['week_number'], ['week_number'], ondelete='RESTRICT')
    # ### end Alembic commands ###
