"""initial_migration

Revision ID: ec77c976dae9
Revises: ad9c21a02dd2
Create Date: 2026-04-12 12:46:14.774698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec77c976dae9'
down_revision: Union[str, Sequence[str], None] = 'ad9c21a02dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_table('workshops',
    sa.Column('workshop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_name', sa.String(length=100), nullable=False),
    sa.Column('tutor_user_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutor_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('workshop_id')
    )
    op.create_index(op.f('ix_workshops_tutor_user_id'), 'workshops', ['tutor_user_id'], unique=False)
    op.create_index(op.f('ix_workshops_workshop_name'), 'workshops', ['workshop_name'], unique=True)
    op.create_table('participation_marks',
    sa.Column('mark_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('marked_by_user_id', sa.String(length=50), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mark_id')
    )
    op.create_index(op.f('ix_participation_marks_marked_by_user_id'), 'participation_marks', ['marked_by_user_id'], unique=False)
    op.create_index(op.f('ix_participation_marks_student_id'), 'participation_marks', ['student_id'], unique=False)
    op.create_index('ix_participation_marks_student_workshop_week', 'participation_marks', ['student_id', 'workshop_id', 'week_number'], unique=False)
    op.create_index(op.f('ix_participation_marks_workshop_id'), 'participation_marks', ['workshop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participation_marks_workshop_id'), table_name='participation_marks')
    op.drop_index('ix_participation_marks_student_workshop_week', table_name='participation_marks')
    op.drop_index(op.f('ix_participation_marks_student_id'), table_name='participation_marks')
    op.drop_index(op.f('ix_participation_marks_marked_by_user_id'), table_name='participation_marks')
    op.drop_table('participation_marks')
    op.drop_index(op.f('ix_workshops_workshop_name'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_tutor_user_id'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
